### PR TITLE
Added extra information in the readme for mock paths parameter

### PR DESCRIPTION
**Pull request by NiLSPACE**
I was confused why my scenario didn't find any commands, but the custom implementations weren't loaded. This info was missing in the readme.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
The links to `AutoAPI.zip` and `ManualAPI.zip` also don't work anymore, but I couldn't find replacement URL's.

**Comment by mathiascode** [comment]
> The links to `AutoAPI.zip` and `ManualAPI.zip` also don't work anymore, but I couldn't find replacement URL's.

Maybe the artifacts had expired? The links work on my end:
- https://ci.appveyor.com/api/projects/cuberite/cuberite/artifacts/AutoAPI.zip?job=Windows-x64&pr=false&branch=master
- https://ci.appveyor.com/api/projects/cuberite/cuberite/artifacts/ManualAPI.zip?job=Windows-x64&pr=false&branch=master

**Review by mathiascode — APPROVED** [review]

**Comment by NiLSPACE** [comment]
The readme refers to

* https://builds.cuberite.org/job/Cuberite%20Windows%20x64%20Master/lastSuccessfulBuild/artifact/AutoAPI.zip
* https://builds.cuberite.org/job/Cuberite%20Windows%20x64%20Master/lastSuccessfulBuild/artifact/ManualAPI.zip

Which both don't work anymore. Shall I change that in this PR as well?

**Comment by mathiascode** [comment]
Sorry, I forgot that the README contains those links. That would be https://github.com/cuberite/CuberitePluginChecker/issues/40.

You could change them. Better to have links that work, even if they're not ideal.

**Pull request merged**
